version: '2'
services:
  common:
    build:
      context: .
    image: sidekiq-cron-test
    environment: &environment
    - REDIS_URL=redis://redis.test:6379/0
    dns:
    - 8.8.8.8
    - 8.8.4.4
  redis:
    image: redis
  tests:
    image: sidekiq-cron-test
    environment: *environment
    links:
    - redis:redis.test
    depends_on:
    - common
    command: dockerize -wait tcp://redis.test:6379 -timeout 60s bundle exec rake test
    volumes:
    - .:/sidekiq-cron
